version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: '128mb'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "6379:6379"

  redisinsight:  # Добавляем RedisInsight URL: redis://default@cache:6379
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"

volumes:
  postgres_data: